name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (from version/version.go)"
        required: false
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Resolve version from version/version.go via binary
        id: ver
        run: |
          ver=$(go run . --version)
          echo "resolved=$ver" >> $GITHUB_OUTPUT
          echo "GORELEASER_CURRENT_TAG=v${ver}" >> $GITHUB_ENV

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


